var sindresorhus = {
    "login": "sindresorhus",
    "id": 170270,
    "avatar_url": "https://avatars.githubusercontent.com/u/170270?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sindresorhus",
    "html_url": "https://github.com/sindresorhus",
    "followers_url": "https://api.github.com/users/sindresorhus/followers",
    "following_url": "https://api.github.com/users/sindresorhus/following{/other_user}",
    "gists_url": "https://api.github.com/users/sindresorhus/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sindresorhus/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sindresorhus/subscriptions",
    "organizations_url": "https://api.github.com/users/sindresorhus/orgs",
    "repos_url": "https://api.github.com/users/sindresorhus/repos",
    "events_url": "https://api.github.com/users/sindresorhus/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sindresorhus/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Sindre Sorhus",
    "company": "ʕ•̫͡•ʔ-̫͡-ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ-̫͡-ʕ•͓͡•ʔ-̫͡-ʔ",
    "blog": "https://twitter.com/sindresorhus",
    "location": "✈",
    "email": "sindresorhus@gmail.com",
    "hireable": null,
    "bio": null,
    "public_repos": 754,
    "public_gists": 59,
    "followers": 11417,
    "following": 39,
    "created_at": "2009-12-20T22:57:02Z",
    "updated_at": "2016-04-22T22:13:17Z",
    "organization": "top_coders"
};

var ruanyf = {
    "login": "ruanyf",
    "id": 905434,
    "avatar_url": "https://avatars.githubusercontent.com/u/905434?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ruanyf",
    "html_url": "https://github.com/ruanyf",
    "followers_url": "https://api.github.com/users/ruanyf/followers",
    "following_url": "https://api.github.com/users/ruanyf/following{/other_user}",
    "gists_url": "https://api.github.com/users/ruanyf/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ruanyf/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ruanyf/subscriptions",
    "organizations_url": "https://api.github.com/users/ruanyf/orgs",
    "repos_url": "https://api.github.com/users/ruanyf/repos",
    "events_url": "https://api.github.com/users/ruanyf/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ruanyf/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Ruan YiFeng",
    "company": null,
    "blog": "https://twitter.com/ruanyf",
    "location": "Shanghai, China",
    "email": "yifeng.ruan@gmail.com",
    "hireable": null,
    "bio": null,
    "public_repos": 30,
    "public_gists": 6,
    "followers": 8422,
    "following": 0,
    "created_at": "2011-07-10T01:07:17Z",
    "updated_at": "2016-04-24T03:58:44Z",
    "organization": "top_coders"
};

var top_coders = [sindresorhus, ruanyf];
exports.top_coders = top_coders;